site_name: c-study-notes

repo_name: c-study-notes
repo_url: https://github.com/Jstbob/c-study-notes.git

theme:
  name: material

nav:
  - index: "index.md"
  - ch08 数组和字符串:
    - 15.  如何在 C 语言中动态分配二维数组？: "ch08 数组和字符串/15.  如何在 C 语言中动态分配二维数组？.md"
    - 16. 如何在 C 中将 2D 数组做为参数传递？: "ch08 数组和字符串/16. 如何在 C 中将 2D 数组做为参数传递？.md"
    - 17-b. C 语言中的多维数组: "ch08 数组和字符串/17-b. C 语言中的多维数组.md"
    - 17. 如何在多行 C 中编写长字符串: "ch08 数组和字符串/17. 如何在多行 C 中编写长字符串.md"
    - 18. 无法创建数组的数据类型有哪些？: "ch08 数组和字符串/18. 无法创建数组的数据类型有哪些？.md"
    - 19. 可变长度数组 VLA: "ch08 数组和字符串/19. 可变长度数组 VLA.md"
    - 20. 快速定义数组中重复的元素: "ch08 数组和字符串/20. 快速定义数组中重复的元素.md"
    - 21. 越界访问数组: "ch08 数组和字符串/21. 越界访问数组.md"
    - 22. 复制字符串: "ch08 数组和字符串/22. 复制字符串.md"
    - 23. 比较字符串: "ch08 数组和字符串/23. 比较字符串.md"
    - 25. 如何按值传递数组？: "ch08 数组和字符串/25. 如何按值传递数组？.md"
    - 26. 反转字符串: "ch08 数组和字符串/26. 反转字符串.md"
    - 27. 字符串操作: "ch08 数组和字符串/27. 字符串操作.md"
  - ch09 控制语句:
    - 9. 在 switch 语句中使用范围匹配: "ch09 控制语句/9. 在 switch 语句中使用范围匹配.md"
  - ch10 函数:
    - 5. 可变长度函数参数的使用: "ch10 函数/5. 可变长度函数参数的使用.md"
  - ch14 文件处理:
    - 2. EOF 和 feof() 的区别: "ch14 文件处理/2. EOF 和 feof() 的区别.md"
    - 3. fopen() 用于写入现有文件: "ch14 文件处理/3. fopen() 用于写入现有文件.md"
